server:
  port: 8083
  session:
    timeout: 2
  servlet:
    context-path: /vegetables

weixin:
    appid: 123456
    key: yeyrew



#alibaba的druid数据库连接池配置
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.92.4.251:3306/vegetables?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        # 使用druid数据源
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        cache: false


mybatis:
  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.weixin.pojo
#  config-location: classpath:mapping/mybatis-config.xml


#日志配置
logging:
  config: classpath:logback.xml

config:
  lkl_jgh: DSFLTJG    #上海拉卡拉机构号
  lkl_BMCP_jgh: 226161   #上海拉卡拉BMCP机构号
  lkl_jgmy: BwMCO6y8Sikj7Jjq8IGDNBvGm5Z3yK9q  #上海拉卡拉机构密钥
  img_drive: C
  http_img_url: http://matou.cabin-tech.com:8082/vegetables/static/fileImg/
#  prod_url: https://eco.taobao.com/router/rest
#  app_key: 23305258
#  app_secret: 29cd2e8efe075b13abe316e8ed87af13
#  sms_type: normal
#  sms_free_sign_name: 一咻停车
#  rec_num: 18757416607
#  sms_template_code: SMS_78595194


logging:
  level:
    com:
      vegetables: DEBUG